service: app-proxy
runtime: python37

instance_class: B8

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10

entrypoint: gunicorn -b 0.0.0.0:8080 main:server

env_variables:
    PSYCOPG2_POSTGRESQL_URI: postgresql://hexmap:manhattan@/postgres?host=/cloudsql/dcms-culture-heritage-map:europe-west2:chc-dcms

beta_settings:
  cloud_sql_instances: dcms-culture-heritage-map:europe-west2:chc-dcms=tcp:5432
